"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Bot, Check, CheckCircle2, CircleCheck, Download, Edit3, ExternalLink, FileText, History, Info, Maximize2, MessageSquareText, Minus, Plus, RotateCcw, ShieldCheck, Sparkles, X } from "lucide-react";
import { reviewFields } from "@/lib/mock-data";

const tabs = ["Extracted fields", "Line items", "Audit trail"] as const;

export function DocumentReview({ documentId = "FP-1048", fileName = "invoice_1048_linella.pdf" }: { documentId?: string; fileName?: string }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Extracted fields");
  const [status, setStatus] = useState<"draft" | "posted" | "rejected">("draft");
  const [zoom, setZoom] = useState(100);
  const [editing, setEditing] = useState<string | null>(null);
  const [values, setValues] = useState(() => Object.fromEntries(reviewFields.map((field) => [field.label, field.value])));

  return (
    <div className="min-h-[calc(100vh-78px)]">
      <div className="border-b border-[#e3e7ee] bg-white px-4 py-4 sm:px-7 lg:px-9">
        <div className="mx-auto flex max-w-[1500px] flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <Link href="/documents" className="focus-ring grid h-9 w-9 place-items-center rounded-xl border border-[#e4e8ef] text-slate-500 hover:bg-slate-50"><ArrowLeft className="h-4 w-4" /></Link>
            <div><div className="flex items-center gap-2"><h1 className="max-w-[290px] truncate text-[15px] font-extrabold text-[#0b1838] sm:max-w-none">{fileName}</h1><span className={`rounded-full border px-2 py-0.5 text-[9px] font-extrabold ${status === "posted" ? "border-emerald-100 bg-emerald-50 text-emerald-700" : status === "rejected" ? "border-rose-100 bg-rose-50 text-rose-700" : "border-sky-100 bg-sky-50 text-sky-700"}`}>{status === "posted" ? "POSTED" : status === "rejected" ? "REJECTED" : "READY TO REVIEW"}</span></div><p className="mt-0.5 text-[9px] font-semibold text-slate-400">{documentId} · Uploaded Sep 28, 2026 at 09:42 by Ana Vlas</p></div>
          </div>
          <div className="flex items-center gap-2 self-end sm:self-auto">
            <button className="focus-ring grid h-9 w-9 place-items-center rounded-xl border border-[#e4e8ef] text-slate-500 hover:bg-slate-50" aria-label="Download original"><Download className="h-4 w-4" /></button>
            {status === "draft" && <><button onClick={() => setStatus("rejected")} className="focus-ring flex h-9 items-center gap-2 rounded-xl border border-[#e4e8ef] bg-white px-3.5 text-[11px] font-extrabold text-slate-600 hover:border-rose-200 hover:text-rose-600"><X className="h-4 w-4" />Reject</button><button onClick={() => setStatus("posted")} className="focus-ring flex h-9 items-center gap-2 rounded-xl bg-[#0b1838] px-4 text-[11px] font-extrabold text-white hover:bg-[#142754]"><Check className="h-4 w-4" />Confirm & post</button></>}
            {status !== "draft" && <button onClick={() => setStatus("draft")} className="focus-ring flex h-9 items-center gap-2 rounded-xl border border-[#e4e8ef] bg-white px-3.5 text-[11px] font-extrabold text-slate-600 hover:bg-slate-50"><RotateCcw className="h-4 w-4" />Reset demo</button>}
          </div>
        </div>
      </div>

      {status === "posted" && <div className="mx-auto max-w-[1500px] px-4 pt-4 sm:px-7 lg:px-9"><div className="animate-float-in flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[11px] font-bold text-emerald-800"><span className="grid h-8 w-8 place-items-center rounded-full bg-emerald-100"><CheckCircle2 className="h-5 w-5" /></span><span className="flex-1"><b className="block text-xs">Accounting entry JE-0284 posted</b><span className="font-medium text-emerald-700">Ledger and analytics were updated. A signed audit event was created.</span></span><Link href="/ledger" className="flex items-center gap-1.5 font-extrabold hover:underline">View entry <ExternalLink className="h-3.5 w-3.5" /></Link></div></div>}
      {status === "rejected" && <div className="mx-auto max-w-[1500px] px-4 pt-4 sm:px-7 lg:px-9"><div className="animate-float-in flex items-center gap-3 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-[11px] font-bold text-rose-800"><X className="h-5 w-5" />Document rejected. No accounting entry was created.</div></div>}

      <div className="mx-auto grid max-w-[1500px] gap-4 px-4 py-4 sm:px-7 lg:grid-cols-[minmax(420px,1fr)_minmax(480px,1fr)] lg:px-9">
        <section className="card-shadow flex min-h-[720px] flex-col overflow-hidden rounded-2xl border border-[#e4e8ef] bg-[#e8ecf3]">
          <div className="flex h-12 items-center justify-between border-b border-[#dfe3ea] bg-white px-4">
            <div className="flex items-center gap-2 text-[10px] font-bold text-slate-500"><FileText className="h-4 w-4 text-[#0a91b8]" />Original document · Page 1 of 1</div>
            <div className="flex items-center gap-1"><button onClick={() => setZoom((value) => Math.max(70, value - 10))} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-50" aria-label="Zoom out"><Minus className="h-3.5 w-3.5" /></button><span className="w-10 text-center text-[9px] font-bold text-slate-500">{zoom}%</span><button onClick={() => setZoom((value) => Math.min(130, value + 10))} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-50" aria-label="Zoom in"><Plus className="h-3.5 w-3.5" /></button><button className="ml-1 rounded-lg p-1.5 text-slate-400 hover:bg-slate-50" aria-label="Full screen"><Maximize2 className="h-3.5 w-3.5" /></button></div>
          </div>
          <div className="flex flex-1 justify-center overflow-auto p-5 sm:p-8">
            <div className="relative h-fit w-full max-w-[520px] origin-top bg-white px-9 py-10 shadow-[0_8px_36px_rgba(35,48,77,0.16)] transition-transform" style={{ transform: `scale(${zoom / 100})` }}>
              <div className="flex items-start justify-between border-b-2 border-[#0b1838] pb-6"><div><div className="text-[24px] font-black tracking-[-0.05em] text-[#0b1838]">LINELLA</div><div className="mt-1 text-[7px] font-bold uppercase tracking-[0.18em] text-slate-400">Market · Moldova</div></div><div className="text-right"><div className="text-[20px] font-extrabold tracking-[-0.04em] text-[#0b1838]">FACTURĂ FISCALĂ</div><div className="mt-1 text-[8px] font-semibold text-slate-500">INV-2026-1048</div></div></div>
              <div className="mt-6 grid grid-cols-2 gap-7 text-[8px] leading-4 text-slate-600"><div><b className="mb-1 block text-[7px] uppercase tracking-wider text-slate-400">Furnizor</b><strong className="text-[10px] text-[#0b1838]">Linella Market SRL</strong><br />str. Industrială 12, Chișinău<br />IDNO: 1003600044118<br />IBAN: MD24AG000000022512449</div><div><b className="mb-1 block text-[7px] uppercase tracking-wider text-slate-400">Cumpărător</b><strong className="text-[10px] text-[#0b1838]">Nordic Retail SRL</strong><br />str. Independenței 44, Chișinău<br />IDNO: 1026600038192<br />Data: 28.09.2026</div></div>
              <table className="mt-7 w-full text-left text-[7px]"><thead><tr className="bg-[#0b1838] text-white"><th className="px-2 py-2">Descriere</th><th className="px-2 py-2 text-right">Cant.</th><th className="px-2 py-2 text-right">Preț</th><th className="px-2 py-2 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-200"><tr><td className="px-2 py-3 font-bold text-[#0b1838]">Produse alimentare — lot A</td><td className="px-2 py-3 text-right">40</td><td className="px-2 py-3 text-right">160.00</td><td className="px-2 py-3 text-right font-bold">6,400.00</td></tr><tr><td className="px-2 py-3 font-bold text-[#0b1838]">Produse alimentare — lot B</td><td className="px-2 py-3 text-right">20</td><td className="px-2 py-3 text-right">200.00</td><td className="px-2 py-3 text-right font-bold">4,000.00</td></tr></tbody></table>
              <div className="ml-auto mt-6 w-[190px] space-y-2 text-[8px]"><div className="flex justify-between text-slate-500"><span>Subtotal</span><b className="text-[#0b1838]">10,400.00 MDL</b></div><div className="flex justify-between text-slate-500"><span>TVA 20%</span><b className="text-[#0b1838]">2,080.00 MDL</b></div><div className="flex justify-between border-t-2 border-[#0b1838] pt-2 text-[11px] font-black text-[#0b1838]"><span>TOTAL</span><span>12,480.00 MDL</span></div></div>
              <div className="mt-11 border-t border-slate-200 pt-5 text-[7px] leading-4 text-slate-400">Termen de plată: 15 zile · Bunurile se livrează conform contractului nr. 18/2026.<div className="mt-7 flex justify-between"><span>Semnătura furnizorului __________________</span><span>L.Ș.</span></div></div>
              <span className="absolute left-[265px] top-[186px] h-[14px] w-[104px] rounded-sm border-2 border-[#1ac5e8] bg-cyan-200/15" title="AI source evidence: supplier" />
              <span className="absolute bottom-[154px] right-[33px] h-[18px] w-[152px] rounded-sm border-2 border-[#6d4df4] bg-violet-200/15" title="AI source evidence: total" />
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <div className="card-shadow overflow-hidden rounded-2xl border border-[#e4e8ef] bg-white">
            <div className="flex items-center border-b border-[#e9ecf2] px-4 pt-2">
              {tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`relative px-3 py-3 text-[10px] font-extrabold ${tab === item ? "text-[#0b1838]" : "text-slate-400 hover:text-slate-600"}`}>{item}{tab === item && <span className="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-[#11bfe7]" />}</button>)}
              <div className="ml-auto flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-extrabold text-emerald-700"><Sparkles className="h-3 w-3" />97% confidence</div>
            </div>
            {tab === "Extracted fields" && <div className="grid gap-x-4 gap-y-3 p-5 sm:grid-cols-2">{reviewFields.map((field) => <label key={field.label} className="group block"><span className="mb-1.5 flex items-center justify-between text-[9px] font-bold text-slate-400"><span>{field.label}</span><span className="text-emerald-600">{field.confidence}%</span></span><span className={`flex h-10 items-center rounded-xl border bg-[#fbfcfe] px-3 transition-colors ${editing === field.label ? "border-[#11bfe7] ring-2 ring-cyan-100" : "border-[#e6e9ef] group-hover:border-slate-300"}`}><input value={values[field.label]} onChange={(e) => setValues({ ...values, [field.label]: e.target.value })} onFocus={() => setEditing(field.label)} onBlur={() => setEditing(null)} className="min-w-0 flex-1 bg-transparent text-[10px] font-bold text-[#0b1838] outline-none" /><Edit3 className="h-3.5 w-3.5 text-slate-300" /></span></label>)}</div>}
            {tab === "Line items" && <div className="p-5"><table className="w-full text-left text-[10px]"><thead><tr className="text-[8px] font-extrabold uppercase tracking-wider text-slate-400"><th className="pb-3">Description</th><th className="pb-3 text-right">Qty</th><th className="pb-3 text-right">Unit price</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100"><tr><td className="py-3 font-bold text-[#0b1838]">Food products — batch A</td><td className="py-3 text-right text-slate-500">40</td><td className="py-3 text-right text-slate-500">160.00</td><td className="py-3 text-right font-bold">6,400.00</td></tr><tr><td className="py-3 font-bold text-[#0b1838]">Food products — batch B</td><td className="py-3 text-right text-slate-500">20</td><td className="py-3 text-right text-slate-500">200.00</td><td className="py-3 text-right font-bold">4,000.00</td></tr></tbody></table></div>}
            {tab === "Audit trail" && <div className="space-y-4 p-5">{[{ icon: CheckCircle2, title: "Extraction completed", time: "09:43:04", text: "8 fields and 2 line items extracted." }, { icon: ShieldCheck, title: "Validation passed", time: "09:43:06", text: "Totals, required fields and duplicate checks passed." }, { icon: Bot, title: "Accounting draft created", time: "09:43:08", text: "Rule AP-INVENTORY-04 · Policy v2.1" }].map((event) => <div key={event.title} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-sky-50 text-sky-600"><event.icon className="h-4 w-4" /></span><div><div className="flex items-center gap-2"><b className="text-[10px] text-[#0b1838]">{event.title}</b><span className="text-[8px] font-semibold text-slate-400">{event.time}</span></div><p className="mt-1 text-[9px] text-slate-500">{event.text}</p></div></div>)}</div>}
          </div>

          <div className="card-shadow rounded-2xl border border-[#e4e8ef] bg-white p-5">
            <div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-50 text-violet-600"><Bot className="h-4 w-4" /></span><div><h2 className="text-[12px] font-extrabold text-[#0b1838]">Proposed accounting entry</h2><p className="text-[9px] font-semibold text-slate-400">Draft · Policy v2.1 · Rule AP-INVENTORY-04</p></div></div></div><button className="flex items-center gap-1 text-[9px] font-bold text-slate-400 hover:text-slate-600"><History className="h-3.5 w-3.5" />History</button></div>
            <div className="mt-5 overflow-hidden rounded-xl border border-[#e8ebf1]"><table className="w-full text-left text-[10px]"><thead><tr className="bg-[#f8fafc] text-[8px] font-extrabold uppercase tracking-wider text-slate-400"><th className="px-3 py-2.5">Account</th><th className="px-3 py-2.5 text-right">Debit</th><th className="px-3 py-2.5 text-right">Credit</th></tr></thead><tbody className="divide-y divide-slate-100"><tr><td className="px-3 py-3"><b className="block text-[#0b1838]">217.1 · Inventory</b><span className="text-[8px] text-slate-400">Goods for resale</span></td><td className="px-3 py-3 text-right font-extrabold text-[#0b1838]">12,480.00</td><td className="px-3 py-3 text-right text-slate-400">—</td></tr><tr><td className="px-3 py-3"><b className="block text-[#0b1838]">521.1 · Trade payables</b><span className="text-[8px] text-slate-400">Linella Market SRL</span></td><td className="px-3 py-3 text-right text-slate-400">—</td><td className="px-3 py-3 text-right font-extrabold text-[#0b1838]">12,480.00</td></tr></tbody><tfoot><tr className="border-t border-[#e5e8ee] bg-[#fbfcfd] font-extrabold text-[#0b1838]"><td className="px-3 py-2.5">Balanced</td><td className="px-3 py-2.5 text-right">12,480.00</td><td className="px-3 py-2.5 text-right">12,480.00</td></tr></tfoot></table></div>
            <div className="mt-4 rounded-xl border border-[#dcecf1] bg-[#f4fbfd] p-3.5"><div className="flex gap-2.5"><MessageSquareText className="mt-0.5 h-4 w-4 shrink-0 text-[#0796bd]" /><div><b className="text-[9px] uppercase tracking-wider text-[#087da3]">Why this entry?</b><p className="mt-1 text-[9px] leading-4 text-slate-600">The supplier invoice contains resale goods and a 20% VAT line. Your company policy maps verified inventory purchases from known suppliers to account 217.1, with the payable recorded on 521.1.</p><button className="mt-2 flex items-center gap-1 text-[9px] font-extrabold text-[#087da3] hover:underline">View policy source <ExternalLink className="h-3 w-3" /></button></div></div></div>
          </div>

          <div className="flex items-start gap-3 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4"><CircleCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600" /><div><b className="text-[10px] text-emerald-800">All deterministic checks passed</b><div className="mt-2 flex flex-wrap gap-2">{["Totals match", "No duplicate", "Known supplier", "Debit = credit"].map((item) => <span key={item} className="flex items-center gap-1 rounded-full bg-white/80 px-2 py-1 text-[8px] font-bold text-emerald-700"><Check className="h-2.5 w-2.5" />{item}</span>)}</div></div><Info className="ml-auto h-4 w-4 text-emerald-400" /></div>
        </section>
      </div>
    </div>
  );
}
