create type public.invoice_direction as enum ('purchase', 'sale');
create type public.invoice_status as enum ('draft', 'confirmed', 'cancelled');
create type public.price_sheet_status as enum ('draft', 'approved', 'cancelled');

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  direction public.invoice_direction not null,
  invoice_number text not null check (char_length(trim(invoice_number)) > 0),
  issue_date date not null,
  counterparty_name text not null check (char_length(trim(counterparty_name)) > 0),
  counterparty_tax_id text,
  currency text not null default 'MDL' check (currency ~ '^[A-Z]{3}$'),
  subtotal numeric(18, 2) not null default 0 check (subtotal >= 0),
  vat_amount numeric(18, 2) not null default 0 check (vat_amount >= 0),
  total_amount numeric(18, 2) not null default 0 check (total_amount >= 0),
  status public.invoice_status not null default 'confirmed',
  source_document_id uuid,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (user_id, direction, invoice_number),
  foreign key (source_document_id, user_id) references public.documents(id, user_id) on delete restrict,
  check (total_amount = subtotal + vat_amount)
);

create table public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  invoice_id uuid not null,
  line_number integer not null check (line_number > 0),
  product_name text not null check (char_length(trim(product_name)) > 0),
  sku text,
  unit text not null default 'buc.',
  quantity numeric(18, 3) not null check (quantity > 0),
  unit_price numeric(18, 4) not null check (unit_price >= 0),
  vat_rate numeric(5, 2) not null default 20 check (vat_rate between 0 and 100),
  subtotal numeric(18, 2) not null check (subtotal >= 0),
  vat_amount numeric(18, 2) not null check (vat_amount >= 0),
  total_amount numeric(18, 2) not null check (total_amount >= 0),
  created_at timestamptz not null default now(),
  unique (id, user_id),
  unique (invoice_id, line_number),
  foreign key (invoice_id, user_id) references public.invoices(id, user_id) on delete cascade,
  check (total_amount = subtotal + vat_amount)
);

create table public.price_sheets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  purchase_invoice_id uuid not null,
  sheet_number bigint generated by default as identity,
  sheet_date date not null,
  status public.price_sheet_status not null default 'approved',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (user_id, sheet_number),
  unique (user_id, purchase_invoice_id),
  foreign key (purchase_invoice_id, user_id) references public.invoices(id, user_id) on delete restrict
);

create table public.price_sheet_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  price_sheet_id uuid not null,
  invoice_item_id uuid not null,
  line_number integer not null check (line_number > 0),
  product_name text not null,
  sku text,
  unit text not null,
  quantity numeric(18, 3) not null check (quantity > 0),
  purchase_price numeric(18, 4) not null check (purchase_price >= 0),
  additional_cost numeric(18, 4) not null default 0 check (additional_cost >= 0),
  markup_percent numeric(7, 2) not null default 0 check (markup_percent >= 0),
  vat_rate numeric(5, 2) not null default 20 check (vat_rate between 0 and 100),
  sale_price numeric(18, 2) not null check (sale_price >= 0),
  created_at timestamptz not null default now(),
  unique (price_sheet_id, line_number),
  foreign key (price_sheet_id, user_id) references public.price_sheets(id, user_id) on delete cascade,
  foreign key (invoice_item_id, user_id) references public.invoice_items(id, user_id) on delete restrict
);

create index invoices_user_date_idx on public.invoices(user_id, direction, issue_date desc);
create index invoice_items_user_invoice_idx on public.invoice_items(user_id, invoice_id);
create index price_sheets_user_date_idx on public.price_sheets(user_id, sheet_date desc);
create index price_sheet_items_user_sheet_idx on public.price_sheet_items(user_id, price_sheet_id);

create trigger invoices_set_updated_at before update on public.invoices for each row execute function private.set_updated_at();
create trigger price_sheets_set_updated_at before update on public.price_sheets for each row execute function private.set_updated_at();

alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;
alter table public.price_sheets enable row level security;
alter table public.price_sheet_items enable row level security;

create policy invoices_own on public.invoices for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy invoice_items_own on public.invoice_items for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy price_sheets_own on public.price_sheets for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy price_sheet_items_own on public.price_sheet_items for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

revoke all on table public.invoices, public.invoice_items, public.price_sheets, public.price_sheet_items from anon, authenticated;
grant select, insert, update, delete on table public.invoices, public.invoice_items, public.price_sheets, public.price_sheet_items to authenticated;
grant usage, select on sequence public.price_sheets_sheet_number_seq to authenticated;

create or replace function public.create_invoice(
  p_direction public.invoice_direction,
  p_invoice_number text,
  p_issue_date date,
  p_counterparty_name text,
  p_counterparty_tax_id text,
  p_currency text,
  p_items jsonb
) returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_invoice_id uuid;
  v_item jsonb;
  v_line integer := 0;
  v_subtotal numeric(18, 2) := 0;
  v_vat numeric(18, 2) := 0;
  v_line_subtotal numeric(18, 2);
  v_line_vat numeric(18, 2);
  v_quantity numeric(18, 3);
  v_unit_price numeric(18, 4);
  v_vat_rate numeric(5, 2);
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if nullif(trim(p_invoice_number), '') is null or nullif(trim(p_counterparty_name), '') is null then raise exception 'invoice header is incomplete'; end if;
  if p_currency !~ '^[A-Z]{3}$' then raise exception 'invalid currency'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'at least one item is required'; end if;

  insert into public.invoices (user_id, direction, invoice_number, issue_date, counterparty_name, counterparty_tax_id, currency)
  values (v_user_id, p_direction, trim(p_invoice_number), p_issue_date, trim(p_counterparty_name), nullif(trim(p_counterparty_tax_id), ''), p_currency)
  returning id into v_invoice_id;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_line := v_line + 1;
    v_quantity := (v_item ->> 'quantity')::numeric;
    v_unit_price := (v_item ->> 'unit_price')::numeric;
    v_vat_rate := coalesce((v_item ->> 'vat_rate')::numeric, 20);
    if nullif(trim(v_item ->> 'product_name'), '') is null or v_quantity <= 0 or v_unit_price < 0 or v_vat_rate < 0 or v_vat_rate > 100 then raise exception 'invalid invoice item'; end if;
    v_line_subtotal := round(v_quantity * v_unit_price, 2);
    v_line_vat := round(v_line_subtotal * v_vat_rate / 100, 2);
    insert into public.invoice_items (user_id, invoice_id, line_number, product_name, sku, unit, quantity, unit_price, vat_rate, subtotal, vat_amount, total_amount)
    values (v_user_id, v_invoice_id, v_line, trim(v_item ->> 'product_name'), nullif(trim(v_item ->> 'sku'), ''), coalesce(nullif(trim(v_item ->> 'unit'), ''), 'buc.'), v_quantity, v_unit_price, v_vat_rate, v_line_subtotal, v_line_vat, v_line_subtotal + v_line_vat);
    v_subtotal := v_subtotal + v_line_subtotal;
    v_vat := v_vat + v_line_vat;
  end loop;

  update public.invoices set subtotal = v_subtotal, vat_amount = v_vat, total_amount = v_subtotal + v_vat where id = v_invoice_id and user_id = v_user_id;
  return v_invoice_id;
end;
$$;

create or replace function public.create_price_sheet(
  p_purchase_invoice_id uuid,
  p_sheet_date date,
  p_markup_percent numeric,
  p_additional_cost numeric
) returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_sheet_id uuid;
  v_item record;
  v_sale_price numeric(18, 2);
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if p_markup_percent < 0 or p_additional_cost < 0 then raise exception 'invalid price parameters'; end if;
  if not exists (select 1 from public.invoices where id = p_purchase_invoice_id and user_id = v_user_id and direction = 'purchase' and status <> 'cancelled') then raise exception 'purchase invoice not found'; end if;

  insert into public.price_sheets (user_id, purchase_invoice_id, sheet_date)
  values (v_user_id, p_purchase_invoice_id, p_sheet_date)
  returning id into v_sheet_id;

  for v_item in select * from public.invoice_items where invoice_id = p_purchase_invoice_id and user_id = v_user_id order by line_number loop
    v_sale_price := round((v_item.unit_price + p_additional_cost) * (1 + p_markup_percent / 100) * (1 + v_item.vat_rate / 100), 2);
    insert into public.price_sheet_items (user_id, price_sheet_id, invoice_item_id, line_number, product_name, sku, unit, quantity, purchase_price, additional_cost, markup_percent, vat_rate, sale_price)
    values (v_user_id, v_sheet_id, v_item.id, v_item.line_number, v_item.product_name, v_item.sku, v_item.unit, v_item.quantity, v_item.unit_price, p_additional_cost, p_markup_percent, v_item.vat_rate, v_sale_price);
  end loop;
  return v_sheet_id;
end;
$$;

revoke all on function public.create_invoice(public.invoice_direction, text, date, text, text, text, jsonb) from public;
revoke all on function public.create_price_sheet(uuid, date, numeric, numeric) from public;
grant execute on function public.create_invoice(public.invoice_direction, text, date, text, text, text, jsonb) to authenticated;
grant execute on function public.create_price_sheet(uuid, date, numeric, numeric) to authenticated;
