create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create type public.organization_role as enum ('owner', 'admin', 'accountant', 'reviewer', 'viewer');
create type public.document_status as enum ('uploaded', 'processing', 'needs_review', 'ready', 'posted', 'failed', 'rejected');
create type public.entry_status as enum ('draft', 'approved', 'posted', 'voided');

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 160),
  idno text,
  base_currency text not null default 'MDL' check (base_currency ~ '^[A-Z]{3}$'),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (idno)
);

create table public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.organization_role not null default 'viewer',
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  original_filename text not null,
  storage_path text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  sha256 text check (sha256 is null or sha256 ~ '^[a-f0-9]{64}$'),
  status public.document_status not null default 'uploaded',
  uploaded_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, storage_path),
  unique (organization_id, sha256)
);

create table public.document_extractions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.documents(id) on delete cascade,
  provider text not null,
  model text,
  extracted_data jsonb not null default '{}'::jsonb,
  confidence numeric(5, 4) check (confidence between 0 and 1),
  created_at timestamptz not null default now(),
  unique (document_id)
);

create table public.ledger_entries (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source_document_id uuid references public.documents(id) on delete restrict,
  entry_number bigint generated by default as identity,
  entry_date date not null,
  description text not null,
  status public.entry_status not null default 'draft',
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  posted_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, entry_number),
  check ((approved_by is null) = (approved_at is null))
);

create table public.ledger_lines (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references public.ledger_entries(id) on delete cascade,
  line_number integer not null check (line_number > 0),
  account_code text not null,
  description text,
  debit numeric(18, 2) not null default 0 check (debit >= 0),
  credit numeric(18, 2) not null default 0 check (credit >= 0),
  currency text not null default 'MDL' check (currency ~ '^[A-Z]{3}$'),
  created_at timestamptz not null default now(),
  unique (entry_id, line_number),
  check ((debit > 0 and credit = 0) or (credit > 0 and debit = 0))
);

create table public.audit_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_id uuid references auth.users(id),
  entity_type text not null,
  entity_id uuid,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index organization_members_user_id_idx on public.organization_members(user_id);
create index documents_organization_created_idx on public.documents(organization_id, created_at desc);
create index documents_status_idx on public.documents(organization_id, status);
create index ledger_entries_organization_date_idx on public.ledger_entries(organization_id, entry_date desc);
create index ledger_lines_entry_id_idx on public.ledger_lines(entry_id);
create index audit_events_organization_created_idx on public.audit_events(organization_id, created_at desc);

create function private.user_organization_ids()
returns setof uuid
language sql
security definer
set search_path = ''
stable
as $$
  select organization_id
  from public.organization_members
  where user_id = (select auth.uid())
$$;

create function private.user_has_organization_role(
  target_organization_id uuid,
  allowed_roles public.organization_role[]
)
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1
    from public.organization_members
    where organization_id = target_organization_id
      and user_id = (select auth.uid())
      and role = any(allowed_roles)
  )
$$;

revoke execute on function private.user_organization_ids() from public;
revoke execute on function private.user_has_organization_role(uuid, public.organization_role[]) from public;
grant execute on function private.user_organization_ids() to authenticated;
grant execute on function private.user_has_organization_role(uuid, public.organization_role[]) to authenticated;

create function public.create_organization(
  organization_name text,
  organization_idno text default null,
  organization_currency text default 'MDL'
)
returns public.organizations
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_organization public.organizations;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required';
  end if;

  insert into public.organizations (name, idno, base_currency, created_by)
  values (
    trim(organization_name),
    nullif(trim(organization_idno), ''),
    upper(organization_currency),
    (select auth.uid())
  )
  returning * into new_organization;

  insert into public.organization_members (organization_id, user_id, role)
  values (new_organization.id, (select auth.uid()), 'owner');

  return new_organization;
end;
$$;

revoke all on function public.create_organization(text, text, text) from public;
grant execute on function public.create_organization(text, text, text) to authenticated;

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger organizations_set_updated_at
before update on public.organizations
for each row execute function private.set_updated_at();

create trigger documents_set_updated_at
before update on public.documents
for each row execute function private.set_updated_at();

create trigger ledger_entries_set_updated_at
before update on public.ledger_entries
for each row execute function private.set_updated_at();

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.documents enable row level security;
alter table public.document_extractions enable row level security;
alter table public.ledger_entries enable row level security;
alter table public.ledger_lines enable row level security;
alter table public.audit_events enable row level security;

create policy organizations_select_members
on public.organizations for select to authenticated
using (id in (select private.user_organization_ids()));

create policy organizations_update_admins
on public.organizations for update to authenticated
using ((select private.user_has_organization_role(id, array['owner', 'admin']::public.organization_role[])))
with check ((select private.user_has_organization_role(id, array['owner', 'admin']::public.organization_role[])));

create policy organization_members_select_members
on public.organization_members for select to authenticated
using (organization_id in (select private.user_organization_ids()));

create policy organization_members_manage_admins
on public.organization_members for all to authenticated
using ((select private.user_has_organization_role(organization_id, array['owner', 'admin']::public.organization_role[])))
with check ((select private.user_has_organization_role(organization_id, array['owner', 'admin']::public.organization_role[])));

create policy documents_select_members
on public.documents for select to authenticated
using (organization_id in (select private.user_organization_ids()));

create policy documents_insert_members
on public.documents for insert to authenticated
with check (
  organization_id in (select private.user_organization_ids())
  and uploaded_by = (select auth.uid())
);

create policy documents_update_reviewers
on public.documents for update to authenticated
using ((select private.user_has_organization_role(organization_id, array['owner', 'admin', 'accountant', 'reviewer']::public.organization_role[])))
with check ((select private.user_has_organization_role(organization_id, array['owner', 'admin', 'accountant', 'reviewer']::public.organization_role[])));

create policy document_extractions_select_members
on public.document_extractions for select to authenticated
using (
  exists (
    select 1 from public.documents
    where documents.id = document_extractions.document_id
      and documents.organization_id in (select private.user_organization_ids())
  )
);

create policy ledger_entries_select_members
on public.ledger_entries for select to authenticated
using (organization_id in (select private.user_organization_ids()));

create policy ledger_entries_insert_accountants
on public.ledger_entries for insert to authenticated
with check (
  (select private.user_has_organization_role(organization_id, array['owner', 'admin', 'accountant']::public.organization_role[]))
  and created_by = (select auth.uid())
);

create policy ledger_entries_update_accountants
on public.ledger_entries for update to authenticated
using ((select private.user_has_organization_role(organization_id, array['owner', 'admin', 'accountant']::public.organization_role[])))
with check ((select private.user_has_organization_role(organization_id, array['owner', 'admin', 'accountant']::public.organization_role[])));

create policy ledger_lines_select_members
on public.ledger_lines for select to authenticated
using (
  exists (
    select 1 from public.ledger_entries
    where ledger_entries.id = ledger_lines.entry_id
      and ledger_entries.organization_id in (select private.user_organization_ids())
  )
);

create policy ledger_lines_write_accountants
on public.ledger_lines for all to authenticated
using (
  exists (
    select 1 from public.ledger_entries
    where ledger_entries.id = ledger_lines.entry_id
      and (select private.user_has_organization_role(ledger_entries.organization_id, array['owner', 'admin', 'accountant']::public.organization_role[]))
  )
)
with check (
  exists (
    select 1 from public.ledger_entries
    where ledger_entries.id = ledger_lines.entry_id
      and (select private.user_has_organization_role(ledger_entries.organization_id, array['owner', 'admin', 'accountant']::public.organization_role[]))
  )
);

create policy audit_events_select_members
on public.audit_events for select to authenticated
using (organization_id in (select private.user_organization_ids()));

revoke all on all tables in schema public from anon;
grant select on public.organizations to authenticated;
grant update (name, idno, base_currency) on public.organizations to authenticated;
grant select, insert, update, delete on public.organization_members to authenticated;
grant select, insert on public.documents to authenticated;
grant update (status) on public.documents to authenticated;
grant select on public.document_extractions to authenticated;
grant select, insert on public.ledger_entries to authenticated;
grant update (source_document_id, entry_date, description, status, approved_by, approved_at, posted_at) on public.ledger_entries to authenticated;
grant select, insert, update, delete on public.ledger_lines to authenticated;
grant select on public.audit_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;
